export const products = [
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Cordless Drill",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Drills",
      price: 129.99,
      sale_price: 99.99,
      on_sale: true,
      in_stock: true,
      quantity: 24,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 342,
      description: "20V MAX cordless drill with 2-speed transmission and LED light.",
      tags: ["cordless", "drill", "20v", "dewalt"],
      slug: "dewalt-20v-max-cordless-drill",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee M18 Circular Saw",
      brand: "Milwaukee",
      category: "Power Tools",
      subcategory: "Saws",
      price: 189.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 10,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 210,
      description: "M18 18V lithium-ion cordless circular saw with 6-1/2 in. blade.",
      tags: ["cordless", "saw", "circular saw", "milwaukee"],
      slug: "milwaukee-m18-circular-saw",
    },
    {
      src: "/placeholder.jpg",
      season: "Fall",
      name: "Husqvarna 450 Rancher Chainsaw",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Chainsaws",
      price: 499.99,
      sale_price: 429.99,
      on_sale: true,
      in_stock: false,
      quantity: 0,
      shipping_available: false,
      in_store_pickup: false,
      rating: 4.9,
      review_count: 189,
      description: "50.2cc chainsaw built for full-time use in demanding conditions.",
      tags: ["chainsaw", "gas", "husqvarna", "outdoor"],
      slug: "husqvarna-450-rancher-chainsaw",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts Turf Builder Lawn Fertilizer",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Fertilizer",
      price: 34.99,
      sale_price: 24.99,
      on_sale: true,
      in_stock: true,
      quantity: 60,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 512,
      description: "Feeds and strengthens grass to protect against future problems.",
      tags: ["lawn", "fertilizer", "scotts", "gardening"],
      slug: "scotts-turf-builder-lawn-fertilizer",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Weber Spirit II E-310 Gas Grill",
      brand: "Weber",
      category: "Patio",
      subcategory: "Grills",
      price: 549.0,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 8,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 430,
      description: "3-burner gas grill with porcelain-enameled cast-iron cooking grates.",
      tags: ["grill", "gas", "weber", "patio", "bbq"],
      slug: "weber-spirit-ii-e-310-gas-grill",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Ortho Home Defense Insect Killer",
      brand: "Ortho",
      category: "Pest Control",
      subcategory: "Insecticide",
      price: 14.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 120,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 870,
      description: "Creates a bug barrier that kills and prevents ants, roaches and spiders.",
      tags: ["pest control", "insect", "ortho", "indoor"],
      slug: "ortho-home-defense-insect-killer",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Carhartt Men's Duck Active Jacket",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Jackets",
      price: 109.99,
      sale_price: 89.99,
      on_sale: true,
      in_stock: true,
      quantity: 35,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 654,
      description: "Durable duck work jacket with blanket lining and multiple pockets.",
      tags: ["jacket", "workwear", "carhartt", "outdoor"],
      slug: "carhartt-mens-duck-active-jacket",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain 14% Beef Cattle Feed 50lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 22.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 200,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 98,
      description: "Complete beef cattle feed with 14% protein for optimal growth.",
      tags: ["feed", "cattle", "farm", "ranch"],
      slug: "big-gain-14-beef-cattle-feed-50lb",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 25ft Tape Measure",
      brand: "DEWALT",
      category: "Hand Tools",
      subcategory: "Measuring Tools",
      price: 24.99,
      sale_price: 19.99,
      on_sale: true,
      in_stock: true,
      quantity: 75,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 320,
      description: "25ft tape measure with magnetic tip and durable nylon-coated blade.",
      tags: ["tape measure", "measuring", "dewalt", "hand tools"],
      slug: "dewalt-25ft-tape-measure",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Husqvarna 21-in Push Lawn Mower",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Lawn Mowers",
      price: 329.99,
      sale_price: null,
      on_sale: false,
      in_stock: false,
      quantity: 0,
      shipping_available: false,
      in_store_pickup: false,
      rating: 4.5,
      review_count: 143,
      description: "163cc engine push mower with 3-in-1 cutting system.",
      tags: ["lawn mower", "push mower", "husqvarna", "outdoor"],
      slug: "husqvarna-21-in-push-lawn-mower",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee Flex Head Ratchet 3/8in",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Ratchets",
      price: 49.99,
      sale_price: 39.99,
      on_sale: true,
      in_stock: true,
      quantity: 42,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 275,
      description: "3/8in drive flex head ratchet with 72-tooth gear system.",
      tags: ["ratchet", "hand tools", "milwaukee"],
      slug: "milwaukee-flex-head-ratchet-38in",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Frigidaire 8000 BTU Window Air Conditioner",
      brand: "Frigidaire",
      category: "Air Conditioning",
      subcategory: "Window Units",
      price: 379.99,
      sale_price: 299.99,
      on_sale: true,
      in_stock: true,
      quantity: 15,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 188,
      description: "Cools a room up to 350 sq ft with easy-to-use mechanical controls.",
      tags: ["air conditioner", "window unit", "cooling", "frigidaire"],
      slug: "frigidaire-8000-btu-window-air-conditioner",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT Impact Driver 20V MAX",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Impact Drivers",
      price: 149.99,
      sale_price: 119.99,
      on_sale: true,
      in_stock: true,
      quantity: 30,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 480,
      description: "Compact and lightweight 20V MAX impact driver with 3 speed settings.",
      tags: ["impact driver", "dewalt", "cordless", "power tools"],
      slug: "dewalt-impact-driver-20v-max",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts EZ Seed Patch and Repair",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Grass Seed",
      price: 29.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 88,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 390,
      description: "Combination mulch, seed and fertilizer that expands with water.",
      tags: ["grass seed", "lawn repair", "scotts", "gardening"],
      slug: "scotts-ez-seed-patch-and-repair",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Carhartt Men's Work Flex Pants",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Pants",
      price: 64.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 55,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 310,
      description: "Relaxed fit work pants with flex technology for all-day comfort.",
      tags: ["pants", "workwear", "carhartt"],
      slug: "carhartt-mens-work-flex-pants",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Weber Performer Deluxe Charcoal Grill",
      brand: "Weber",
      category: "Patio",
      subcategory: "Grills",
      price: 449.0,
      sale_price: 379.0,
      on_sale: true,
      in_stock: true,
      quantity: 6,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 265,
      description: "22-inch charcoal grill with touch-n-go gas ignition system.",
      tags: ["grill", "charcoal", "weber", "patio"],
      slug: "weber-performer-deluxe-charcoal-grill",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Ortho WeedClear Lawn Weed Killer",
      brand: "Ortho",
      category: "Gardening",
      subcategory: "Weed Killer",
      price: 19.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 95,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.2,
      review_count: 430,
      description: "Kills over 200 weeds including dandelion and clover, won't harm grass.",
      tags: ["weed killer", "lawn", "ortho", "gardening"],
      slug: "ortho-weedclear-lawn-weed-killer",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Milwaukee M12 Heated Jacket",
      brand: "Milwaukee",
      category: "Work Wear",
      subcategory: "Jackets",
      price: 199.99,
      sale_price: 159.99,
      on_sale: true,
      in_stock: true,
      quantity: 20,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 520,
      description: "M12 heated jacket with carbon fiber heating elements across chest and back.",
      tags: ["heated jacket", "workwear", "milwaukee", "winter"],
      slug: "milwaukee-m12-heated-jacket",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Chicken Layer Feed 50lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 18.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 150,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 76,
      description: "Complete layer feed formulated for optimal egg production.",
      tags: ["chicken feed", "poultry", "farm", "big gain"],
      slug: "big-gain-chicken-layer-feed-50lb",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Husqvarna 330iX Battery Trimmer",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Trimmers",
      price: 279.99,
      sale_price: 229.99,
      on_sale: true,
      in_stock: true,
      quantity: 18,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 134,
      description: "Battery powered trimmer with auto-cutting head and low noise level.",
      tags: ["trimmer", "battery", "husqvarna", "outdoor"],
      slug: "husqvarna-330ix-battery-trimmer",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 7-1/4in Circular Saw",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Saws",
      price: 89.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 22,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 290,
      description: "15-amp motor circular saw with carbide blade and electric brake.",
      tags: ["circular saw", "dewalt", "power tools", "corded"],
      slug: "dewalt-7-14in-circular-saw",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Patio Dining Set 5-Piece",
      brand: "Hampton Bay",
      category: "Patio",
      subcategory: "Furniture",
      price: 599.0,
      sale_price: 449.0,
      on_sale: true,
      in_stock: true,
      quantity: 4,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 112,
      description: "5-piece outdoor dining set with rust-resistant aluminum frame.",
      tags: ["patio furniture", "dining set", "outdoor"],
      slug: "patio-dining-set-5-piece",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Ortho Bug B Gon Insect Killer",
      brand: "Ortho",
      category: "Pest Control",
      subcategory: "Insecticide",
      price: 12.99,
      sale_price: 9.99,
      on_sale: true,
      in_stock: true,
      quantity: 200,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 640,
      description: "Kills over 235 insects including ants, mosquitoes and fleas.",
      tags: ["pest control", "insecticide", "ortho", "outdoor"],
      slug: "ortho-bug-b-gon-insect-killer",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee 6-Piece Combination Wrench Set",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Wrenches",
      price: 39.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 50,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 195,
      description: "6-piece SAE combination wrench set with off-corner loading design.",
      tags: ["wrench", "hand tools", "milwaukee"],
      slug: "milwaukee-6-piece-combination-wrench-set",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Frigidaire 12000 BTU Portable AC",
      brand: "Frigidaire",
      category: "Air Conditioning",
      subcategory: "Portable Units",
      price: 499.99,
      sale_price: 399.99,
      on_sale: true,
      in_stock: true,
      quantity: 9,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.2,
      review_count: 230,
      description: "Portable air conditioner cools up to 550 sq ft with remote control.",
      tags: ["air conditioner", "portable", "cooling", "frigidaire"],
      slug: "frigidaire-12000-btu-portable-ac",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Horse Sweet Feed 50lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 26.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 80,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 54,
      description: "Textured sweet feed for horses with added vitamins and minerals.",
      tags: ["horse feed", "sweet feed", "farm", "big gain"],
      slug: "big-gain-horse-sweet-feed-50lb",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Carhartt Men's Steel Toe Work Boot",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Boots",
      price: 139.99,
      sale_price: 109.99,
      on_sale: true,
      in_stock: true,
      quantity: 28,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 445,
      description: "Waterproof steel toe work boot with cement construction and oil-tanned leather.",
      tags: ["boots", "steel toe", "carhartt", "workwear"],
      slug: "carhartt-mens-steel-toe-work-boot",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT Random Orbit Sander",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Sanders",
      price: 59.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 33,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 178,
      description: "5-inch random orbit sander with 8-hole hook and lock pad.",
      tags: ["sander", "dewalt", "power tools", "corded"],
      slug: "dewalt-random-orbit-sander",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Husqvarna Automower 315 Robotic Mower",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Lawn Mowers",
      price: 1299.99,
      sale_price: 999.99,
      on_sale: true,
      in_stock: false,
      quantity: 0,
      shipping_available: false,
      in_store_pickup: false,
      rating: 4.7,
      review_count: 88,
      description: "Robotic lawn mower for yards up to 0.4 acres with GPS navigation.",
      tags: ["robotic mower", "husqvarna", "outdoor", "automatic"],
      slug: "husqvarna-automower-315-robotic-mower",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts Snap Spreader System",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Spreaders",
      price: 49.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 40,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 210,
      description: "No-mess, no-guess snap spreader with interchangeable product cartridges.",
      tags: ["spreader", "lawn", "scotts", "gardening"],
      slug: "scotts-snap-spreader-system",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee Hacksaw 12in",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Saws",
      price: 29.99,
      sale_price: 22.99,
      on_sale: true,
      in_stock: true,
      quantity: 60,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 145,
      description: "12-inch hacksaw with high-tension frame and bi-metal blade.",
      tags: ["hacksaw", "hand tools", "milwaukee", "cutting"],
      slug: "milwaukee-hacksaw-12in",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Patio Umbrella 9ft",
      brand: "Hampton Bay",
      category: "Patio",
      subcategory: "Umbrellas",
      price: 89.99,
      sale_price: 69.99,
      on_sale: true,
      in_stock: true,
      quantity: 25,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 320,
      description: "9ft crank and tilt patio umbrella with UV-resistant canopy.",
      tags: ["umbrella", "patio", "outdoor", "shade"],
      slug: "patio-umbrella-9ft",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Ortho GroundClear Vegetation Killer",
      brand: "Ortho",
      category: "Pest Control",
      subcategory: "Herbicide",
      price: 17.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 110,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.1,
      review_count: 380,
      description: "Kills all vegetation and prevents regrowth for up to 12 months.",
      tags: ["herbicide", "weed killer", "ortho", "pest control"],
      slug: "ortho-groundclear-vegetation-killer",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Frigidaire 5000 BTU Window AC",
      brand: "Frigidaire",
      category: "Air Conditioning",
      subcategory: "Window Units",
      price: 199.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 20,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 290,
      description: "5000 BTU window air conditioner for rooms up to 150 sq ft.",
      tags: ["air conditioner", "window unit", "frigidaire", "cooling"],
      slug: "frigidaire-5000-btu-window-ac",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Jigsaw",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Saws",
      price: 119.99,
      sale_price: 94.99,
      on_sale: true,
      in_stock: true,
      quantity: 16,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 198,
      description: "Cordless jigsaw with 4-position orbital action and tool-free blade change.",
      tags: ["jigsaw", "dewalt", "cordless", "power tools"],
      slug: "dewalt-20v-max-jigsaw",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain All Purpose Livestock Mineral",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Supplements",
      price: 32.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 65,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 42,
      description: "All-purpose loose mineral supplement for beef and dairy cattle.",
      tags: ["mineral", "supplement", "farm", "livestock", "big gain"],
      slug: "big-gain-all-purpose-livestock-mineral",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Carhartt Men's Thermal Henley",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Shirts",
      price: 34.99,
      sale_price: 27.99,
      on_sale: true,
      in_stock: true,
      quantity: 70,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 530,
      description: "Midweight cotton thermal henley with three-button placket.",
      tags: ["thermal", "shirt", "carhartt", "workwear", "winter"],
      slug: "carhartt-mens-thermal-henley",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee Magnetic Level 48in",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Levels",
      price: 44.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 38,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 167,
      description: "48-inch magnetic level with 3 vials and aluminum box frame.",
      tags: ["level", "hand tools", "milwaukee", "measuring"],
      slug: "milwaukee-magnetic-level-48in",
    },
    {
      src: "/placeholder.jpg",
      season: "Fall",
      name: "Husqvarna 350BT Gas Backpack Blower",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Blowers",
      price: 299.99,
      sale_price: 249.99,
      on_sale: true,
      in_stock: true,
      quantity: 12,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 155,
      description: "50.2cc backpack blower with X-Torq engine for low emissions.",
      tags: ["blower", "backpack", "husqvarna", "outdoor", "gas"],
      slug: "husqvarna-350bt-gas-backpack-blower",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts Liquid Turf Builder Lawn Food",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Fertilizer",
      price: 21.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 75,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 285,
      description: "Liquid lawn fertilizer that feeds and greens in just 24 hours.",
      tags: ["fertilizer", "liquid", "scotts", "lawn", "gardening"],
      slug: "scotts-liquid-turf-builder-lawn-food",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Weber Smokey Mountain Cooker 18in",
      brand: "Weber",
      category: "Patio",
      subcategory: "Smokers",
      price: 399.0,
      sale_price: 329.0,
      on_sale: true,
      in_stock: true,
      quantity: 7,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 340,
      description: "18-inch charcoal smoker with two cooking grates and built-in thermometer.",
      tags: ["smoker", "charcoal", "weber", "patio", "bbq"],
      slug: "weber-smokey-mountain-cooker-18in",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Ortho Bed Bug Killer Spray",
      brand: "Ortho",
      category: "Pest Control",
      subcategory: "Insecticide",
      price: 9.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 180,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.0,
      review_count: 720,
      description: "Kills bed bugs and their eggs on contact, for use on mattresses and furniture.",
      tags: ["bed bugs", "pest control", "ortho", "indoor"],
      slug: "ortho-bed-bug-killer-spray",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT Oscillating Multi-Tool 20V",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Multi-Tools",
      price: 139.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 19,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 212,
      description: "20V MAX oscillating tool with quick-change accessory system.",
      tags: ["oscillating", "multi-tool", "dewalt", "cordless"],
      slug: "dewalt-oscillating-multi-tool-20v",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Carhartt Men's Work Gloves",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Gloves",
      price: 24.99,
      sale_price: 18.99,
      on_sale: true,
      in_stock: true,
      quantity: 90,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 610,
      description: "Synthetic leather palm gloves with moisture wicking lining.",
      tags: ["gloves", "workwear", "carhartt"],
      slug: "carhartt-mens-work-gloves",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Frigidaire Through-Wall AC 10000 BTU",
      brand: "Frigidaire",
      category: "Air Conditioning",
      subcategory: "Through-Wall Units",
      price: 449.99,
      sale_price: null,
      on_sale: false,
      in_stock: false,
      quantity: 0,
      shipping_available: false,
      in_store_pickup: false,
      rating: 4.3,
      review_count: 142,
      description: "Through-the-wall air conditioner with 10000 BTU cooling power.",
      tags: ["air conditioner", "through wall", "frigidaire", "cooling"],
      slug: "frigidaire-through-wall-ac-10000-btu",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Pig Grower Feed 50lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 20.99,
      sale_price: 16.99,
      on_sale: true,
      in_stock: true,
      quantity: 100,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 38,
      description: "Nutritionally complete grower feed for pigs from 40 to 125 lbs.",
      tags: ["pig feed", "swine", "farm", "big gain"],
      slug: "big-gain-pig-grower-feed-50lb",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee 10-Piece Screwdriver Set",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Screwdrivers",
      price: 34.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 55,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 390,
      description: "10-piece screwdriver set with cushion grip handles and magnetic tips.",
      tags: ["screwdriver", "hand tools", "milwaukee"],
      slug: "milwaukee-10-piece-screwdriver-set",
    },
    {
      src: "/placeholder.jpg",
      season: "Fall",
      name: "Husqvarna 125B Handheld Blower",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Blowers",
      price: 139.99,
      sale_price: 109.99,
      on_sale: true,
      in_stock: true,
      quantity: 22,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 198,
      description: "28cc handheld gas blower with cruise control and ergonomic design.",
      tags: ["blower", "handheld", "husqvarna", "outdoor", "gas"],
      slug: "husqvarna-125b-handheld-blower",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Patio Adirondack Chair Set of 2",
      brand: "Hampton Bay",
      category: "Patio",
      subcategory: "Furniture",
      price: 179.0,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 14,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 225,
      description: "Set of 2 all-weather Adirondack chairs made from recycled plastic.",
      tags: ["adirondack", "chair", "patio", "outdoor", "furniture"],
      slug: "patio-adirondack-chair-set-of-2",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts Weed and Feed 5000 sq ft",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Weed Killer",
      price: 39.99,
      sale_price: 29.99,
      on_sale: true,
      in_stock: true,
      quantity: 48,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 670,
      description: "Kills over 45 weeds while feeding and thickening your lawn.",
      tags: ["weed and feed", "lawn", "scotts", "gardening", "fertilizer"],
      slug: "scotts-weed-and-feed-5000-sq-ft",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Angle Grinder",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Grinders",
      price: 89.99,
      sale_price: 69.99,
      on_sale: true,
      in_stock: true,
      quantity: 20,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 215,
      description: "4-1/2 inch cordless angle grinder with paddle switch and kickback brake.",
      tags: ["angle grinder", "dewalt", "cordless", "power tools"],
      slug: "dewalt-20v-max-angle-grinder",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Carhartt Men's Insulated Bib Overalls",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Overalls",
      price: 149.99,
      sale_price: 119.99,
      on_sale: true,
      in_stock: true,
      quantity: 30,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 340,
      description: "Quilt-lined bib overalls with triple-stitched seams and multiple pockets.",
      tags: ["overalls", "insulated", "carhartt", "winter", "workwear"],
      slug: "carhartt-mens-insulated-bib-overalls",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Weber Genesis EX-335 Smart Grill",
      brand: "Weber",
      category: "Patio",
      subcategory: "Grills",
      price: 1099.0,
      sale_price: 899.0,
      on_sale: true,
      in_stock: true,
      quantity: 5,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 178,
      description: "Smart gas grill with built-in thermometer and app connectivity.",
      tags: ["grill", "smart", "weber", "patio", "gas"],
      slug: "weber-genesis-ex-335-smart-grill",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts DiseaseEx Lawn Fungicide",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Fungicide",
      price: 24.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 55,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 198,
      description: "Controls and prevents 26 lawn diseases including brown patch and dollar spot.",
      tags: ["fungicide", "lawn", "scotts", "gardening"],
      slug: "scotts-diseaseex-lawn-fungicide",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee Pliers Set 3-Piece",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Pliers",
      price: 44.99,
      sale_price: 34.99,
      on_sale: true,
      in_stock: true,
      quantity: 48,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 290,
      description: "3-piece pliers set including linesman, long nose, and diagonal cutting pliers.",
      tags: ["pliers", "hand tools", "milwaukee"],
      slug: "milwaukee-pliers-set-3-piece",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Frigidaire Gallery 18 cu ft Refrigerator",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Refrigerators",
      price: 899.99,
      sale_price: 749.99,
      on_sale: true,
      in_stock: true,
      quantity: 6,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 132,
      description: "18 cu ft top freezer refrigerator with even-temperature cooling.",
      tags: ["refrigerator", "frigidaire", "appliance"],
      slug: "frigidaire-gallery-18-cu-ft-refrigerator",
    },
    {
      src: "/placeholder.jpg",
      season: "Fall",
      name: "Husqvarna 460 Rancher Chainsaw 24in",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Chainsaws",
      price: 599.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 9,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 145,
      description: "60.3cc professional chainsaw with 24-inch bar for demanding applications.",
      tags: ["chainsaw", "gas", "husqvarna", "outdoor", "professional"],
      slug: "husqvarna-460-rancher-chainsaw-24in",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Turkey Grower Feed 50lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 21.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 85,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 32,
      description: "Complete grower feed formulated for turkeys from 8 weeks to market.",
      tags: ["turkey feed", "poultry", "farm", "big gain"],
      slug: "big-gain-turkey-grower-feed-50lb",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Reciprocating Saw",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Saws",
      price: 109.99,
      sale_price: 84.99,
      on_sale: true,
      in_stock: true,
      quantity: 25,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 267,
      description: "Cordless reciprocating saw with keyless blade change and 4-position blade clamp.",
      tags: ["reciprocating saw", "dewalt", "cordless", "power tools"],
      slug: "dewalt-20v-max-reciprocating-saw",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Ortho Max Poison Ivy Killer",
      brand: "Ortho",
      category: "Pest Control",
      subcategory: "Herbicide",
      price: 16.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 130,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.2,
      review_count: 410,
      description: "Kills poison ivy, poison oak and more down to the root.",
      tags: ["herbicide", "poison ivy", "ortho", "outdoor"],
      slug: "ortho-max-poison-ivy-killer",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Carhartt Men's Arctic Quilt Lined Vest",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Vests",
      price: 84.99,
      sale_price: 64.99,
      on_sale: true,
      in_stock: true,
      quantity: 40,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 285,
      description: "Duck vest with Arctic-weight quilt lining and multiple utility pockets.",
      tags: ["vest", "insulated", "carhartt", "winter", "workwear"],
      slug: "carhartt-mens-arctic-quilt-lined-vest",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee 9Ah Battery Pack",
      brand: "Milwaukee",
      category: "Power Tools",
      subcategory: "Batteries",
      price: 149.99,
      sale_price: 119.99,
      on_sale: true,
      in_stock: true,
      quantity: 35,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 445,
      description: "M18 REDLITHIUM 9.0Ah battery pack with fuel gauge and onboard storage.",
      tags: ["battery", "milwaukee", "m18", "power tools"],
      slug: "milwaukee-9ah-battery-pack",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Hampton Bay 11ft Offset Patio Umbrella",
      brand: "Hampton Bay",
      category: "Patio",
      subcategory: "Umbrellas",
      price: 199.99,
      sale_price: 159.99,
      on_sale: true,
      in_stock: true,
      quantity: 12,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 198,
      description: "11ft offset cantilever umbrella with 360-degree rotation and crank lift.",
      tags: ["umbrella", "offset", "patio", "hampton bay", "shade"],
      slug: "hampton-bay-11ft-offset-patio-umbrella",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts Turf Builder Grass Seed Sun & Shade",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Grass Seed",
      price: 44.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 65,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 380,
      description: "Grows in full sun and dense shade with WaterSmart coating.",
      tags: ["grass seed", "sun shade", "scotts", "gardening"],
      slug: "scotts-turf-builder-grass-seed-sun-shade",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT Tool Bag 16in",
      brand: "DEWALT",
      category: "Hand Tools",
      subcategory: "Storage",
      price: 34.99,
      sale_price: 27.99,
      on_sale: true,
      in_stock: true,
      quantity: 55,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 320,
      description: "16-inch open top tool bag with 33 pockets and water-resistant base.",
      tags: ["tool bag", "storage", "dewalt", "hand tools"],
      slug: "dewalt-tool-bag-16in",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Frigidaire 30in Electric Range",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Ranges",
      price: 649.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 4,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 89,
      description: "30-inch electric range with self-cleaning oven and 5 heating elements.",
      tags: ["range", "electric", "frigidaire", "appliance"],
      slug: "frigidaire-30in-electric-range",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Husqvarna 130BT Gas Backpack Blower",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Blowers",
      price: 199.99,
      sale_price: 169.99,
      on_sale: true,
      in_stock: true,
      quantity: 14,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 122,
      description: "27.1cc backpack blower with hip-mounted throttle control.",
      tags: ["blower", "backpack", "husqvarna", "outdoor", "gas"],
      slug: "husqvarna-130bt-gas-backpack-blower",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Rabbit Pellet Feed 25lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 14.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 120,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 28,
      description: "Complete pelleted feed for rabbits with balanced fiber and protein.",
      tags: ["rabbit feed", "small animal", "farm", "big gain"],
      slug: "big-gain-rabbit-pellet-feed-25lb",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee 8-Piece Drill Bit Set",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Drill Bits",
      price: 29.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 70,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 234,
      description: "8-piece black oxide drill bit set with split point tip for fast starts.",
      tags: ["drill bits", "hand tools", "milwaukee"],
      slug: "milwaukee-8-piece-drill-bit-set",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Weber Traveler Portable Gas Grill",
      brand: "Weber",
      category: "Patio",
      subcategory: "Grills",
      price: 299.0,
      sale_price: 249.0,
      on_sale: true,
      in_stock: true,
      quantity: 10,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 210,
      description: "Portable gas grill with 320 sq in cooking area and collapsible stand.",
      tags: ["portable grill", "gas", "weber", "patio", "camping"],
      slug: "weber-traveler-portable-gas-grill",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Brad Nailer",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Nailers",
      price: 199.99,
      sale_price: 159.99,
      on_sale: true,
      in_stock: true,
      quantity: 18,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 188,
      description: "18-gauge brad nailer with tool-free depth adjustment and jam release.",
      tags: ["nailer", "brad nailer", "dewalt", "cordless"],
      slug: "dewalt-20v-max-brad-nailer",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Carhartt Men's Knit Hat",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Hats",
      price: 19.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 110,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 890,
      description: "Acrylic watch hat with firm-knit construction and fold-up cuff.",
      tags: ["hat", "beanie", "carhartt", "winter", "workwear"],
      slug: "carhartt-mens-knit-hat",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Ortho Flower Fruit and Vegetable Spray",
      brand: "Ortho",
      category: "Gardening",
      subcategory: "Insecticide",
      price: 11.99,
      sale_price: 8.99,
      on_sale: true,
      in_stock: true,
      quantity: 145,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.1,
      review_count: 320,
      description: "Kills aphids, caterpillars, and other insects on edible plants.",
      tags: ["insecticide", "garden", "ortho", "spray"],
      slug: "ortho-flower-fruit-and-vegetable-spray",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee Heavy Duty Staple Gun",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Staple Guns",
      price: 39.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 42,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 155,
      description: "Heavy duty staple gun compatible with 4 staple sizes and brad nails.",
      tags: ["staple gun", "hand tools", "milwaukee"],
      slug: "milwaukee-heavy-duty-staple-gun",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Hampton Bay Stationary Fire Pit",
      brand: "Hampton Bay",
      category: "Patio",
      subcategory: "Fire Pits",
      price: 149.0,
      sale_price: 119.0,
      on_sale: true,
      in_stock: true,
      quantity: 16,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 245,
      description: "35-inch round wood-burning fire pit with spark screen and poker.",
      tags: ["fire pit", "patio", "hampton bay", "outdoor"],
      slug: "hampton-bay-stationary-fire-pit",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Husqvarna Battery Chainsaw 14in",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Chainsaws",
      price: 349.99,
      sale_price: 299.99,
      on_sale: true,
      in_stock: true,
      quantity: 11,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 98,
      description: "Battery-powered 14-inch chainsaw with brushless motor and auto-oiling.",
      tags: ["chainsaw", "battery", "husqvarna", "outdoor"],
      slug: "husqvarna-battery-chainsaw-14in",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts Miracle-Gro Garden Soil",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Soil",
      price: 12.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 200,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 540,
      description: "In-ground garden soil enriched with compost for flowers and vegetables.",
      tags: ["soil", "garden", "scotts", "gardening"],
      slug: "scotts-miracle-gro-garden-soil",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Circular Saw Combo Kit",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Combo Kits",
      price: 299.99,
      sale_price: 239.99,
      on_sale: true,
      in_stock: true,
      quantity: 14,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 312,
      description: "2-tool combo kit with drill/driver and circular saw plus 2 batteries.",
      tags: ["combo kit", "dewalt", "cordless", "power tools"],
      slug: "dewalt-20v-max-circular-saw-combo-kit",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Goat Feed 50lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 23.99,
      sale_price: 19.99,
      on_sale: true,
      in_stock: true,
      quantity: 90,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 45,
      description: "Complete pelleted feed for goats with added vitamins and minerals.",
      tags: ["goat feed", "farm", "ranch", "big gain"],
      slug: "big-gain-goat-feed-50lb",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Frigidaire 30in Over-Range Microwave",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Microwaves",
      price: 299.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 8,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 112,
      description: "1.9 cu ft over-the-range microwave with 1000 watts and sensor cooking.",
      tags: ["microwave", "frigidaire", "appliance", "over range"],
      slug: "frigidaire-30in-over-range-microwave",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee 6ft Folding Rule",
      brand: "Milwaukee",
      category: "Hand Tools",
      subcategory: "Measuring Tools",
      price: 19.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 60,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 178,
      description: "6-foot folding rule with inside reading and brass extension slide.",
      tags: ["folding rule", "measuring", "milwaukee", "hand tools"],
      slug: "milwaukee-6ft-folding-rule",
    },
    {
      src: "/placeholder.jpg",
      season: "Fall",
      name: "Husqvarna 967 Riding Lawn Mower 42in",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Riding Mowers",
      price: 1799.99,
      sale_price: 1599.99,
      on_sale: true,
      in_stock: false,
      quantity: 0,
      shipping_available: false,
      in_store_pickup: false,
      rating: 4.8,
      review_count: 67,
      description: "42-inch riding lawn mower with 18.5 HP Briggs engine and air induction.",
      tags: ["riding mower", "husqvarna", "outdoor", "lawn"],
      slug: "husqvarna-967-riding-lawn-mower-42in",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Carhartt Men's Base Force Cold Weather Crew",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Base Layers",
      price: 44.99,
      sale_price: 34.99,
      on_sale: true,
      in_stock: true,
      quantity: 65,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 420,
      description: "Heavyweight base layer crew with FastDry technology for cold weather.",
      tags: ["base layer", "thermal", "carhartt", "winter", "workwear"],
      slug: "carhartt-mens-base-force-cold-weather-crew",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Ortho Mosquito B Gon Yard Spray",
      brand: "Ortho",
      category: "Pest Control",
      subcategory: "Insecticide",
      price: 18.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 95,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 560,
      description: "Kills mosquitoes and prevents re-infestation for up to 6 weeks.",
      tags: ["mosquito", "pest control", "ortho", "outdoor"],
      slug: "ortho-mosquito-b-gon-yard-spray",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 6-Piece Screwdriving Set",
      brand: "DEWALT",
      category: "Hand Tools",
      subcategory: "Screwdrivers",
      price: 22.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 80,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 245,
      description: "6-piece screwdriver set with ergonomic bi-material handles.",
      tags: ["screwdriver", "hand tools", "dewalt"],
      slug: "dewalt-6-piece-screwdriving-set",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Hampton Bay 3-Piece Outdoor Sectional",
      brand: "Hampton Bay",
      category: "Patio",
      subcategory: "Furniture",
      price: 799.0,
      sale_price: 649.0,
      on_sale: true,
      in_stock: true,
      quantity: 3,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 88,
      description: "3-piece outdoor sectional sofa with all-weather wicker and cushions.",
      tags: ["sectional", "patio furniture", "outdoor", "hampton bay"],
      slug: "hampton-bay-3-piece-outdoor-sectional",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee M18 Drill Driver",
      brand: "Milwaukee",
      category: "Power Tools",
      subcategory: "Drills",
      price: 169.99,
      sale_price: 139.99,
      on_sale: true,
      in_stock: true,
      quantity: 28,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 398,
      description: "M18 1/2-inch drill driver with 60 Nm of torque and all-metal chuck.",
      tags: ["drill", "milwaukee", "m18", "cordless"],
      slug: "milwaukee-m18-drill-driver",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Scotts Turf Builder EdgeGuard Mini Spreader",
      brand: "Scotts",
      category: "Gardening",
      subcategory: "Spreaders",
      price: 34.99,
      sale_price: 27.99,
      on_sale: true,
      in_stock: true,
      quantity: 45,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 290,
      description: "Mini broadcast spreader with EdgeGuard technology for precise application.",
      tags: ["spreader", "lawn", "scotts", "gardening"],
      slug: "scotts-turf-builder-edgeguard-mini-spreader",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Sheep and Goat Mineral",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Supplements",
      price: 28.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 55,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 38,
      description: "Loose mineral supplement formulated for sheep and goats.",
      tags: ["mineral", "supplement", "farm", "sheep", "goat", "big gain"],
      slug: "big-gain-sheep-and-goat-mineral",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Frigidaire 26 cu ft Side-By-Side Refrigerator",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Refrigerators",
      price: 1199.99,
      sale_price: 999.99,
      on_sale: true,
      in_stock: true,
      quantity: 3,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 76,
      description: "26 cu ft side-by-side refrigerator with water and ice dispenser.",
      tags: ["refrigerator", "side by side", "frigidaire", "appliance"],
      slug: "frigidaire-26-cu-ft-side-by-side-refrigerator",
    },
    {
      src: "/placeholder.jpg",
      season: "Fall",
      name: "Husqvarna 220iL Battery String Trimmer",
      brand: "Husqvarna",
      category: "Outdoor Equipment",
      subcategory: "Trimmers",
      price: 199.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 16,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 112,
      description: "Battery string trimmer with straight shaft and auto-cut head.",
      tags: ["trimmer", "battery", "husqvarna", "outdoor"],
      slug: "husqvarna-220il-battery-string-trimmer",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Router",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Routers",
      price: 179.99,
      sale_price: 149.99,
      on_sale: true,
      in_stock: true,
      quantity: 12,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.7,
      review_count: 143,
      description: "Compact cordless router with dual LEDs and 1-1/4 HP motor.",
      tags: ["router", "dewalt", "cordless", "power tools", "woodworking"],
      slug: "dewalt-20v-max-router",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Weber Kettle Premium Charcoal Grill 22in",
      brand: "Weber",
      category: "Patio",
      subcategory: "Grills",
      price: 219.0,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 14,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 650,
      description: "Classic 22-inch kettle grill with one-touch cleaning system and lid thermometer.",
      tags: ["kettle grill", "charcoal", "weber", "patio"],
      slug: "weber-kettle-premium-charcoal-grill-22in",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Carhartt Men's Rigby Short Sleeve Tee",
      brand: "Carhartt",
      category: "Work Wear",
      subcategory: "Shirts",
      price: 24.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 95,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 710,
      description: "Relaxed fit workwear tee with moisture-wicking fabric and UV protection.",
      tags: ["t-shirt", "workwear", "carhartt"],
      slug: "carhartt-mens-rigby-short-sleeve-tee",
    },
    {
      src: "/placeholder.jpg",
      season: "Spring",
      name: "Ortho Elementals Lawn Weed Killer",
      brand: "Ortho",
      category: "Gardening",
      subcategory: "Weed Killer",
      price: 22.99,
      sale_price: 17.99,
      on_sale: true,
      in_stock: true,
      quantity: 85,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.2,
      review_count: 267,
      description: "OMRI listed organic weed killer safe for use around people and pets.",
      tags: ["weed killer", "organic", "ortho", "gardening"],
      slug: "ortho-elementals-lawn-weed-killer",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Milwaukee M18 Rotary Hammer",
      brand: "Milwaukee",
      category: "Power Tools",
      subcategory: "Rotary Hammers",
      price: 299.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 10,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.9,
      review_count: 167,
      description: "SDS-plus rotary hammer with 2.0 ft-lbs of impact energy and FIXTEC chuck.",
      tags: ["rotary hammer", "milwaukee", "m18", "cordless"],
      slug: "milwaukee-m18-rotary-hammer",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Big Gain Duck and Geese Feed 50lb",
      brand: "Big Gain",
      category: "Farm & Ranch",
      subcategory: "Animal Feed",
      price: 19.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 75,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 22,
      description: "Complete pelleted feed for ducks and geese with added niacin.",
      tags: ["duck feed", "geese feed", "poultry", "farm", "big gain"],
      slug: "big-gain-duck-and-geese-feed-50lb",
    },
    {
      src: "/placeholder.jpg",
      season: "Summer",
      name: "Hampton Bay Outdoor Chaise Lounge Set of 2",
      brand: "Hampton Bay",
      category: "Patio",
      subcategory: "Furniture",
      price: 399.0,
      sale_price: 319.0,
      on_sale: true,
      in_stock: true,
      quantity: 6,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 134,
      description: "Set of 2 adjustable outdoor chaise lounges with quick-dry cushions.",
      tags: ["chaise lounge", "patio furniture", "outdoor", "hampton bay"],
      slug: "hampton-bay-outdoor-chaise-lounge-set-of-2",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "DEWALT 20V MAX Hammer Drill",
      brand: "DEWALT",
      category: "Power Tools",
      subcategory: "Drills",
      price: 159.99,
      sale_price: 129.99,
      on_sale: true,
      in_stock: true,
      quantity: 22,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.8,
      review_count: 355,
      description: "20V MAX XR cordless hammer drill with 3-mode operation and LED light.",
      tags: ["hammer drill", "dewalt", "cordless", "power tools"],
      slug: "dewalt-20v-max-hammer-drill",
    },
    {
      src: "/placeholder.jpg",
      season: "Winter",
      name: "Frigidaire 30in Gas Range",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Ranges",
      price: 749.99,
      sale_price: 599.99,
      on_sale: true,
      in_stock: true,
      quantity: 5,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.5,
      review_count: 98,
      description: "30-inch gas range with 5 sealed burners and quick boil element.",
      tags: ["range", "gas", "frigidaire", "appliance"],
      slug: "frigidaire-30in-gas-range",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Frigidaire 24in Built-In Dishwasher",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Dishwashers",
      price: 549.99,
      sale_price: 449.99,
      on_sale: true,
      in_stock: true,
      quantity: 7,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 112,
      description: "24-inch built-in dishwasher with 14 place settings and OrbitClean wash arm.",
      tags: ["dishwasher", "frigidaire", "appliance"],
      slug: "frigidaire-24in-built-in-dishwasher",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Frigidaire Top Load Washer 4.1 cu ft",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Washers",
      price: 699.99,
      sale_price: null,
      on_sale: false,
      in_stock: true,
      quantity: 5,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 88,
      description: "4.1 cu ft top load washer with multiple wash cycles and delay start.",
      tags: ["washer", "laundry", "frigidaire", "appliance"],
      slug: "frigidaire-top-load-washer-41-cu-ft",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Frigidaire Electric Dryer 6.7 cu ft",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Dryers",
      price: 649.99,
      sale_price: 549.99,
      on_sale: true,
      in_stock: true,
      quantity: 5,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.4,
      review_count: 76,
      description: "6.7 cu ft electric dryer with sensor dry and wrinkle release option.",
      tags: ["dryer", "laundry", "frigidaire", "appliance"],
      slug: "frigidaire-electric-dryer-67-cu-ft",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Frigidaire 1.6 cu ft Countertop Microwave",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Microwaves",
      price: 179.99,
      sale_price: 139.99,
      on_sale: true,
      in_stock: true,
      quantity: 18,
      shipping_available: true,
      in_store_pickup: true,
      rating: 4.3,
      review_count: 145,
      description: "1.6 cu ft countertop microwave with 1100 watts and easy-set controls.",
      tags: ["microwave", "countertop", "frigidaire", "appliance"],
      slug: "frigidaire-16-cu-ft-countertop-microwave",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Frigidaire 30in Wall Oven Electric",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Wall Ovens",
      price: 899.99,
      sale_price: null,
      on_sale: false,
      in_stock: false,
      quantity: 0,
      shipping_available: false,
      in_store_pickup: false,
      rating: 4.5,
      review_count: 54,
      description: "30-inch single electric wall oven with true convection and self-clean.",
      tags: ["wall oven", "electric", "frigidaire", "appliance"],
      slug: "frigidaire-30in-wall-oven-electric",
    },
    {
      src: "/placeholder.jpg",
      season: "All",
      name: "Frigidaire 20 cu ft French Door Refrigerator",
      brand: "Frigidaire",
      category: "Appliances",
      subcategory: "Refrigerators",
      price: 1299.99,
      sale_price: 1099.99,
      on_sale: true,
      in_stock: true,
      quantity: 4,
      shipping_available: false,
      in_store_pickup: true,
      rating: 4.6,
      review_count: 93,
      description: "20 cu ft french door refrigerator with filtered ice maker and humidity-controlled crispers.",
      tags: ["refrigerator", "french door", "frigidaire", "appliance"],
      slug: "frigidaire-20-cu-ft-french-door-refrigerator",
    },
  ];